export const countryCurrencySymbols = [
  {
    country: "United States",
    language: "English",
    languageAbbreviation: "en",
    currency: "US Dollar",
    symbolCode: "&#36;", // Dollar sign ($)
    abbreviation: "USD",
    icon: "https://img.icons8.com/color/96/usa-circular.png",
  },
  {
    country: "Eurozone",
    language: "English",
    languageAbbreviation: "en",
    currency: "Euro",
    symbolCode: "&#8364;", // Euro sign (€)
    abbreviation: "EUR",
    icon: "https://img.icons8.com/color/96/great-britain-circular.png",
  },
  {
    country: "India",
    language: "English",
    languageAbbreviation: "en",
    currency: "Indian Rupee",
    symbolCode: "&#8377;", // Indian Rupee (₹)
    abbreviation: "INR",
    icon: "https://img.icons8.com/color/96/india-circular.png",
  },
  {
    country: "Saudi Arabia",
    language: "Arabic",
    languageAbbreviation: "ar",
    currency: "Saudi Riyal",
    symbolCode: "&#65020;", // Riyal sign (﷼)
    abbreviation: "SAR",
    icon: "https://img.icons8.com/color/96/saudi-arabia-circular.png",
  },
  {
    country: "United Arab Emirates",
    language: "Arabic",
    languageAbbreviation: "ar",
    currency: "UAE Dirham",
    symbolCode: "&#x62f;&#x2e;&#x625;", // Dirham sign (د.إ)
    abbreviation: "AED",
    icon: "https://img.icons8.com/color/96/united-arab-emirates-circular.png",
  },
  {
    country: "Germany",
    language: "German",
    languageAbbreviation: "de",
    currency: "Euro",
    symbolCode: "&#8364;", // Euro sign (€)
    abbreviation: "EUR",
    icon: "https://img.icons8.com/color/96/germany-circular.png",
  },
  {
    country: "France",
    language: "French",
    languageAbbreviation: "fr",
    currency: "Euro",
    symbolCode: "&#8364;", // Euro sign (€)
    abbreviation: "EUR",
    icon: "https://img.icons8.com/color/96/france-circular.png",
  },
  {
    country: "Italy",
    language: "Italian",
    languageAbbreviation: "it",
    currency: "Euro",
    symbolCode: "&#8364;", // Euro sign (€)
    abbreviation: "EUR",
    icon: "https://img.icons8.com/color/96/italy-circular.png",
  },
  {
    country: "Afghanistan",
    language: "Pashto",
    languageAbbreviation: "ps",
    currency: "Afghani",
    symbolCode: "&#8387;", // Afghani sign (؋)
    abbreviation: "AFN",
    icon: "https://img.icons8.com/color/96/afghanistan-flag-circle.png",
  },
  {
    country: "Albania",
    language: "Albanian",
    languageAbbreviation: "sq",
    currency: "Albanian Lek",
    symbolCode: "&#76;", // Lek sign (L)
    abbreviation: "ALL",
    icon: "https://img.icons8.com/color/96/albania-circular.png",
  },
  {
    country: "Algeria",
    language: "Arabic",
    languageAbbreviation: "ar",
    currency: "Algerian Dinar",
    symbolCode: "&#8360;", // Dinar sign (دج)
    abbreviation: "DZD",
    icon: "https://img.icons8.com/color/96/algeria-circular.png",
  },
  {
    country: "Andorra",
    language: "Catalan",
    languageAbbreviation: "ca",
    currency: "Euro",
    symbolCode: "&#8364;", // Euro sign (€)
    abbreviation: "EUR",
    icon: "https://phoenix.sirv.com/aragon-flag.png",
  },
  {
    country: "Angola",
    language: "Portuguese",
    languageAbbreviation: "pt",
    currency: "Angolan Kwanza",
    symbolCode: "&#75;", // Kwanza sign (Kz)
    abbreviation: "AOA",
    icon: "https://img.icons8.com/color/96/angola-circular.png",
  },
  {
    country: "Antigua and Barbuda",
    language: "English",
    languageAbbreviation: "en",
    currency: "East Caribbean Dollar",
    symbolCode: "&#8378;", // East Caribbean Dollar sign (XCD)
    abbreviation: "XCD",
    icon: "https://img.icons8.com/color/96/antigua-and-barbuda-circular.png",
  },
  {
    country: "India",
    language: "Hindi",
    languageAbbreviation: "hi",
    currency: "Indian Rupee",
    symbolCode: "&#8377;", // Indian Rupee (₹)
    abbreviation: "INR",
    icon: "https://img.icons8.com/color/96/india-circular.png",
  },
  {
    country: "Canada",
    language: "English",
    languageAbbreviation: "en",
    currency: "Canadian Dollar",
    symbolCode: "C$",
    abbreviation: "CAD",
    icon: "https://img.icons8.com/color/96/canada-circular.png",
  },
  {
    country: "United Kingdom",
    language: "English",
    languageAbbreviation: "en",
    currency: "Pound Sterling",
    symbolCode: "£",
    abbreviation: "GBP",
    icon: "https://img.icons8.com/color/96/united-kingdom-circular.png",
  },
  {
    country: "China",
    language: "Mandarin",
    languageAbbreviation: "zh",
    currency: "Chinese Yuan",
    symbolCode: "¥",
    abbreviation: "CNY",
    icon: "https://img.icons8.com/color/96/china-circular.png",
  },
  {
    country: "Japan",
    language: "Japanese",
    languageAbbreviation: "ja",
    currency: "Japanese Yen",
    symbolCode: "¥",
    abbreviation: "JPY",
    icon: "https://img.icons8.com/color/96/japan-circular.png",
  },
  {
    country: "Brazil",
    language: "Portuguese",
    languageAbbreviation: "pt",
    currency: "Brazilian Real",
    symbolCode: "R$",
    abbreviation: "BRL",
    icon: "https://img.icons8.com/color/96/brazil-circular.png",
  },
  {
    country: "Russia",
    language: "Russian",
    languageAbbreviation: "ru",
    currency: "Russian Ruble",
    symbolCode: "₽",
    abbreviation: "RUB",
    icon: "https://img.icons8.com/color/96/russian-federation-circular.png",
  },
  {
    country: "Germany",
    language: "German",
    languageAbbreviation: "de",
    currency: "Euro",
    symbolCode: "€",
    abbreviation: "EUR",
    icon: "https://img.icons8.com/color/96/germany-circular.png",
  },
  {
    country: "France",
    language: "French",
    languageAbbreviation: "fr",
    currency: "Euro",
    symbolCode: "€",
    abbreviation: "EUR",
    icon: "https://img.icons8.com/color/96/france-circular.png",
  },
  {
    country: "South Korea",
    language: "Korean",
    languageAbbreviation: "ko",
    currency: "South Korean Won",
    symbolCode: "₩",
    abbreviation: "KRW",
    icon: "https://img.icons8.com/color/96/south-korea-circular.png",
  },
  {
    country: "Mexico",
    language: "Spanish",
    languageAbbreviation: "es",
    currency: "Mexican Peso",
    symbolCode: "$",
    abbreviation: "MXN",
    icon: "https://img.icons8.com/color/96/mexico-circular.png",
  },
  {
    country: "Italy",
    language: "Italian",
    languageAbbreviation: "it",
    currency: "Euro",
    symbolCode: "€",
    abbreviation: "EUR",
    icon: "https://img.icons8.com/color/96/italy-circular.png",
  },
  {
    country: "Spain",
    language: "Spanish",
    languageAbbreviation: "es",
    currency: "Euro",
    symbolCode: "€",
    abbreviation: "EUR",
    icon: "https://img.icons8.com/color/96/spain-circular.png",
  },
  {
    country: "Indonesia",
    language: "Indonesian",
    languageAbbreviation: "id",
    currency: "Indonesian Rupiah",
    symbolCode: "Rp",
    abbreviation: "IDR",
    icon: "https://img.icons8.com/color/96/indonesia-circular.png",
  },
  {
    country: "Turkey",
    language: "Turkish",
    languageAbbreviation: "tr",
    currency: "Turkish Lira",
    symbolCode: "₺",
    abbreviation: "TRY",
    icon: "https://img.icons8.com/color/96/turkey-circular.png",
  },
  {
    country: "Saudi Arabia",
    language: "Arabic",
    languageAbbreviation: "ar",
    currency: "Saudi Riyal",
    symbolCode: "﷼",
    abbreviation: "SAR",
    icon: "https://img.icons8.com/color/96/saudi-arabia-circular.png",
  },
  {
    country: "South Africa",
    language: "Afrikaans",
    languageAbbreviation: "af",
    currency: "South African Rand",
    symbolCode: "R",
    abbreviation: "ZAR",
    icon: "https://img.icons8.com/color/96/south-africa-circular.png",
  },
  {
    country: "Nigeria",
    language: "English",
    languageAbbreviation: "en",
    currency: "Nigerian Naira",
    symbolCode: "₦",
    abbreviation: "NGN",
    icon: "https://img.icons8.com/color/96/nigeria-circular.png",
  },
  {
    country: "Egypt",
    language: "Arabic",
    languageAbbreviation: "ar",
    currency: "Egyptian Pound",
    symbolCode: "E£",
    abbreviation: "EGP",
    icon: "https://img.icons8.com/color/96/egypt-circular.png",
  },
  {
    country: "Argentina",
    language: "Spanish",
    languageAbbreviation: "es",
    currency: "Argentine Peso",
    symbolCode: "$",
    abbreviation: "ARS",
    icon: "https://img.icons8.com/color/96/argentina-circular.png",
  },
  {
    country: "Sweden",
    language: "Swedish",
    languageAbbreviation: "sv",
    currency: "Swedish Krona",
    symbolCode: "kr",
    abbreviation: "SEK",
    icon: "https://img.icons8.com/color/96/sweden-circular.png",
  },
  {
    country: "Norway",
    language: "Norwegian",
    languageAbbreviation: "no",
    currency: "Norwegian Krone",
    symbolCode: "kr",
    abbreviation: "NOK",
    icon: "https://img.icons8.com/color/96/norway-circular.png",
  },
  {
    country: "Switzerland",
    language: "German",
    languageAbbreviation: "de",
    currency: "Swiss Franc",
    symbolCode: "Fr.",
    abbreviation: "CHF",
    icon: "https://img.icons8.com/color/96/switzerland-circular.png",
  },
  {
    country: "Singapore",
    language: "English",
    languageAbbreviation: "en",
    currency: "Singapore Dollar",
    symbolCode: "S$",
    abbreviation: "SGD",
    icon: "https://img.icons8.com/color/96/singapore-circular.png",
  },
  {
    country: "United Arab Emirates",
    language: "Arabic",
    languageAbbreviation: "ar",
    currency: "UAE Dirham",
    symbolCode: "د.إ",
    abbreviation: "AED",
    icon: "https://img.icons8.com/color/96/united-arab-emirates-circular.png",
  },
  {
    country: "Israel",
    language: "Hebrew",
    languageAbbreviation: "he",
    currency: "Israeli New Shekel",
    symbolCode: "₪",
    abbreviation: "ILS",
    icon: "https://img.icons8.com/color/96/israel-circular.png",
  },
  {
    country: "New Zealand",
    language: "English, Māori",
    languageAbbreviation: "en, mi",
    currency: "New Zealand Dollar",
    symbolCode: "NZ$",
    abbreviation: "NZD",
    icon: "https://img.icons8.com/color/96/new-zealand-circular.png",
  },
  {
    country: "Chile",
    language: "Spanish",
    languageAbbreviation: "es",
    currency: "Chilean Peso",
    symbolCode: "$",
    abbreviation: "CLP",
    icon: "https://img.icons8.com/color/96/chile-circular.png",
  },
];
